### PR TITLE
About page

### PR DESCRIPTION
**Pull request by durandom**
This fixes the linking in the navbar and adds the about page for reference.
If you need to search for examples look at https://github.com/search?l=JavaScript&q=import+header+mantine%2Fcore+import+link+gatsby&type=Code

### CODE REVIEW

**Comment by durandom** [comment]
https://github.com/search?l=JavaScript&q=import+header+mantine%2Fcore+import+link+gatsby&type=Code

**Comment by durandom** [comment]
@schwesig @hemajv @aakankshaduggal @bryanmontalvan pls review

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Pull request merged**
