### PR TITLE
Fixed spacing between buttons and responsiveness

### PR DESCRIPTION
**Pull request by bryanmontalvan**
## Description
This PR works upon/continues the work from #17 

**Changes:**
- Fixed spacing between buttons
- Fixed width and spacing for smaller devices (Mobile responsiveness)
- Fixed padding on description text on smaller devices

**Mobile Previews:**

image

### CODE REVIEW

**Comment by stefwrite** [comment]
That works for me, Bryan.

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Pull request merged**
